### ISSUE TITLE
p1-build-the-GUI

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#1]
Please mark as DONE as you progress through the below

~00 - what-is-expected-and-what-is-not-expected-in-p1.txt~

~01 - the scope.txt~

~02 - gulp-build.txt~

~03 - application-menu.txt~

~05 - configuration-general.txt~

~10 - cloud-email-providers.txt~

~15 - configuration-email-settings.txt~

~20 - configuration-email-message.txt~

~25 - configuration-email-larger.txt~

~30 - configuration-email-attachments.txt~

~35 - configuration-advanced.txt~

~40 - configuration-templates.txt~

~45 - do-action.txt~

~50 - quality.txt~

~55 - logging-tracing.txt~

~60 - upload.txt~

**Comment by luismanuel001** [comment]
Done with all views, please test.
