### ISSUE TITLE
070 - Packaging

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#18]
Please update the readme.md with instructions how to use the package-win, package-linux and package-osx task to generate "self-contained" zip files (specific for the OS). The output of running these task should be a self-contained zip file specific to the OS.

self-contained = If I extract the TheProtonApp.zip file and then I double click TheProtonApp.exe ==> the app should work (out of the box) without having to install anything else.

copy paste from 02 - gulp-build.txt

_Packaging

Following gulp tasks should be available and should work fine

package-win, package-mac, package-linux and each package-* task
should package the zip file with all needed files for the specific OS_

**Comment by luismanuel001** [comment]
Please test now
