### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#22]
![npm-install](https://cloud.githubusercontent.com/assets/19224635/22828794/93865ac8-ef9f-11e6-9277-49ee4ebb91bc.png)

**Comment by distributev** [comment]
![npm-install-2](https://cloud.githubusercontent.com/assets/19224635/22828980/6cca788c-efa0-11e6-8231-7f7ed4f9ddb6.png)

**Comment by luismanuel001** [comment]
Yes I'm currently trying to solve this problem.
