### ISSUE TITLE
025 - Implement the Well-Known Services popups (views)

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#7]
![issue06](https://cloud.githubusercontent.com/assets/19224635/22499774/02be45ea-e861-11e6-9653-ee1fbb7304d1.png)

**Comment by luismanuel001** [comment]
@distributev I thought these will come on p2, do you need me to implement only the popups, or filling in the info on the parent view also?

**Comment by distributev** [comment]
Only the GUI popups for now and make the correct popups to come when the buttons are clicked.

The logic to fill the parent view in p2.
