### ISSUE TITLE
035 - Screens are too small

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#9]
I compared the new application with the original application and it's much smaller (pixel sizez of the screens). Make sure to respect the pixel sizes from 03 - application-menu.png (from the initial requirements).

![issue08](https://cloud.githubusercontent.com/assets/19224635/22500218/636a8a14-e863-11e6-9cae-c190cd564b58.png)

**Comment by luismanuel001** [comment]
On `03 - application-menu.png` it says that the windows should be 960px(width) by 650px(height), and those are the dimensions I specified in code, (you can verify [here](https://github.com/distributev/the-proton/blob/master/src/background.js#L39-L42) in the code), and you can see thats true on the following screenshot:

![screen shot 2017-02-01 at 1 58 29 pm](https://cloud.githubusercontent.com/assets/847539/22519711/c66f88ca-e887-11e6-9a1a-71533b39b6fd.png)

**Comment by distributev** [comment]
Something strange is happening. See the new screenshot. For me it shows 754px vs. 510px. I also compared the new app window alongside the existing app which I know for sure it's 960px(width) by 650px(height) and the new windows is considerable smaller.

What do you think is happening?

![754vs510](https://cloud.githubusercontent.com/assets/19224635/22558977/ead1ddec-e96f-11e6-8acc-d31185561dc0.png)
